FROM python:3.6

RUN pip install adal kubernetes msrestazure

RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash \
    && helm version

COPY ./install_arc_agents/install_arc_agents.py /

COPY ./common/arm_rest_utility.py /

COPY ./common/helm_utility.py /

COPY ./common/results_utility.py /

CMD ["python", "./install_arc_agents.py"]