FROM python:3.6

RUN pip install adal msrestazure azure-mgmt-hybridkubernetes junit_xml

COPY ./check_cluster_metadata/check_cluster_metadata.py /

COPY ./common/arm_rest_utility.py /

COPY ./common/connected_cluster_utility.py /

COPY ./common/results_utility.py /

CMD ["python", "./check_cluster_metadata.py"]