FROM python:3.6

RUN pip install kubernetes junit_xml

COPY ./check_kubernetes_pods/check_pods_status.py /

COPY ./common/results_utility.py /

COPY ./common/kubernetes_pod_utility.py /

CMD ["python", "./check_pods_status.py"]