FROM python:3.6

RUN pip install kubernetes

COPY ./check_arc_agent_pods/check_pod_status.py /

COPY ./common/results_utility.py /

COPY ./common/kubernetes_pod_utility.py /

CMD ["python", "./check_pod_status.py"]
