FROM python:3.6

RUN pip install kubernetes junit_xml

COPY ./check_pod_logs/check_pod_logs.py /

COPY ./common/results_utility.py /

COPY ./common/kubernetes_pod_utility.py /

CMD ["python", "./check_pod_logs.py"]