sonobuoy-config:
  driver: Job
  plugin-name: check-kubernetes-configuration
  result-format: junit
spec:
  image: akashkeshari3010/arc-conformance-test:check-kubernetes-configv01
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results
