FROM python:3.6

RUN pip install adal msrestazure azure-mgmt-kubernetesconfiguration junit_xml

COPY ./check_kubernetes_configuration/check_kubernetes_configuration.py /

COPY ./common/arm_rest_utility.py /

COPY ./common/kubernetes_configuration_utility.py /

COPY ./common/results_utility.py /

CMD ["python", "./check_kubernetes_configuration.py"]