FROM python:3.6

RUN pip install kubernetes junit_xml

COPY ./check_kubernetes_secret/check_kubernetes_secret.py /

COPY ./common/results_utility.py /

COPY ./common/kubernetes_secret_utility.py /

CMD ["python", "./check_kubernetes_secret.py"]