FROM python:3.6

RUN pip install kubernetes junit_xml

COPY ./check_crd_status/check_crd_status.py /

COPY ./common/results_utility.py /

COPY ./common/kubernetes_crd_utility.py /

CMD ["python", "./check_crd_status.py"]